"""Render the implementation registry for human review; never awards coverage."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]


def report(registry):
    features = registry["features"]
    completed = sum(f["status"] == "verified" for f in features)
    assert len(features) == registry["target"] == 167
    assert completed == registry["verified"]
    lines = ["# Inkbolt implementation report", "", f"**{completed}/167 verified ({completed/167*100:.2f}%).**", "", "Scope: agent-generated diagrams, icons, layouts, image edits and exports, followed by the full vector and raster capability set. All 167 original checkpoints remain required. The percentage counts complete, independently verified checkpoints; it does not estimate remaining effort or award partial work.", "", "| Lane | Verified | Total | Completion |", "| --- | ---: | ---: | ---: |"]
    for lane in ("vector", "raster"):
        group = [f for f in features if f["id"].startswith(lane+".")]
        count = sum(f["status"] == "verified" for f in group)
        lines.append(f"| {lane.title()} | {count} | {len(group)} | {count/len(group)*100:.2f}% |")
    pending = [f for f in features if f["status"] != "verified"]
    lines += ["", f"## Remaining work ({len(pending)} checkpoints)", "", "| ID | Status | Original acceptance |", "| --- | --- | --- |"]
    for f in pending:
        lines.append(f"| {f['id']} | {f['status']} | {f['acceptance']} |")
    native = next(f for f in features if f["id"] == "vector.prepress.extended")
    lines += ["", "## Print preparation", "", f"Status: **{native['status']}**. Native process and spot separations, profile conversion, flattened PDF pages and physical print marks include masks, compositing, filters, retained source objects and explicit shared inks. Declared HDR source views and process-colour adjustment layers have explicit conversion contracts; see [source contexts](NATIVE_CONTEXTS.md), [native adjustments](NATIVE_ADJUSTMENTS.md) and [plate delivery](VECTOR_PLATES.md). Registry status governs checkpoint credit.", "", "## Full scope and evidence", "", "A verified checkpoint has complete acceptance coverage and named executable evidence. In-progress work receives zero points. The registry is available through `implementation.status`. This table is generated by `python tools/update_report.py` from features.json.", "", "| ID | Status | Acceptance | Evidence |", "| --- | --- | --- | --- |"]
    for feature in features:
        evidence = "; ".join(f"`{e}`" for e in feature["evidence"]) or "Pending"
        lines.append(f"| {feature['id']} | {feature['status']} | {feature['acceptance']} | {evidence} |")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    registry = json.loads((ROOT/"docs/features.json").read_text(encoding="utf8"))
    (ROOT/"docs/IMPLEMENTATION.md").write_text(report(registry), encoding="utf8")
    print(f"Report: {registry['verified']}/167 ({registry['percent']:.2f}%).")
